### PR TITLE
test(infra): Add custom assertions library

### LINKED ISSUE #561: [Testing] Custom Assertions Library
Test Infrastructure: Custom Assertions Library
===============================================

PRIORITY: MEDIUM
COMPLEXITY: Low
ESTIMATED EFFORT: 2-3 hours
CATEGORY: Testing Infrastructure
LABEL: testing,infrastructure,priority:medium

OBJECTIVE
---------
Create custom assertions library for common Wanaku-specific validation patterns,
providing clear failure messages and reducing test code duplication.

CURRENT STATE
-------------
- Generic AssertJ assertions used
- Duplicated assertion logic across tests
- Unclear failure messages

IMPLEMENTATION
--------------

File: tests/integration/src/test/java/ai/wanaku/test/assertions/WanakuAssertions.java

```java
package ai.wanaku.test.assertions;

import ai.wanaku.model.*;
import io.restassured.response.Response;
import org.testcontainers.containers.GenericContainer;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Custom assertions for Wanaku testing.
 * Provides domain-specific assertions with clear failure messages.
 */
public class WanakuAssertions {

    // ========== Response Assertions ==========

    public static void assertSuccessResponse(WanakuResponse<?> response) {
        assertThat(response).isNotNull();
        assertThat(response.isSuccess())
            .withFailMessage("Expected success response but got error: %s",
                response.getError())
            .isTrue();
        assertThat(response.getError()).isNull();
    }

    public static void assertErrorResponse(WanakuResponse<?> response) {
        assertThat(response).isNotNull();
        assertThat(response.isSuccess())
            .withFailMessage("Expected error response but got success")
            .isFalse();
        assertThat(response.getError()).isNotNull();
    }

    public static void assertErrorResponse(WanakuResponse<?> response, String expectedMessage) {
        assertErrorResponse(response);
        assertThat(response.getError())
            .withFailMessage("Expected error message to contain '%s' but got: %s",
                expectedMessage, response.getError())
            .contains(expectedMessage);
    }

    // ========== HTTP Response Assertions ==========

    public static void assertHttpStatus(Response response, int expectedStatus) {
        int actualStatus = response.getStatusCode();
        assertThat(actualStatus)
            .withFailMessage("Expected HTTP status %d but got %d. Response body: %s",
                expectedStatus, actualStatus, getResponseBody(response))
            .isEqualTo(expectedStatus);
    }

    public static void assertHttpSuccess(Response response) {
        int status = response.getStatusCode();
        assertThat(status)
            .withFailMessage("Expected successful HTTP status (2xx) but got %d. Response: %s",
                status, getResponseBody(response))
            .isBetween(200, 299);
    }

    public static void assertHttpError(Response response) {
        int status = response.getStatusCode();
        assertThat(status)
            .withFailMessage("Expected error HTTP status (4xx or 5xx) but got %d",
                status)
            .isGreaterThanOrEqualTo(400);
    }

    // ========== Tool Assertions ==========

    public static void assertToolRegistered(String toolName, List<ToolReference> tools) {
        assertThat(tools)
            .withFailMessage("Expected tool '%s' to be registered but it was not found in: %s",
                toolName, getToolNames(tools))
            .extracting(ToolReference::getName)
            .contains(toolName);
    }

    public static void assertToolNotRegistered(String toolName, List<ToolReference> tools) {
        assertThat(tools)
            .withFailMessage("Expected tool '%s' to NOT be registered but it was found",
                toolName)
            .extracting(ToolReference::getName)
            .doesNotContain(toolName);
    }

    public static void assertToolEquals(ToolReference expected, ToolReference actual) {
        assertThat(actual)
            .withFailMessage("Expected tool to match but it didn't")
            .isNotNull();
        assertThat(actual.getName()).isEqualTo(expected.getName());
        assertThat(actual.getNamespace()).isEqualTo(expected.getNamespace());
        assertThat(actual.getType()).isEqualTo(expected.getType());
        assertThat(actual.getUri()).isEqualTo(expected.getUri());
    }

    // ========== Resource Assertions ==========

    public static void assertResourceRegistered(String resourceName,
                                                 List<ResourceReference> resources) {
        assertThat(resources)
            .withFailMessage("Expected resource '%s' to be registered but it was not found in: %s",
                resourceName, getResourceNames(resources))
            .extracting(ResourceReference::getName)
            .contains(resourceName);
    }

    public static void assertResourceNotRegistered(String resourceName,
                                                    List<ResourceReference> resources) {
        assertThat(resources)
            .withFailMessage("Expected resource '%s' to NOT be registered but it was found",
                resourceName)
            .extracting(ResourceReference::getName)
            .doesNotContain(resourceName);
    }

    public static void assertResourceEquals(ResourceReference expected, ResourceReference actual) {
        assertThat(actual).isNotNull();
        assertThat(actual.getName()).isEqualTo(expected.getName());
        assertThat(actual.getNamespace()).isEqualTo(expected.getNamespace());
        assertThat(actual.getUri()).isEqualTo(expected.getUri());
        assertThat(actual.getMimeType()).isEqualTo(expected.getMimeType());
    }

    // ========== Forward Assertions ==========

    public static void assertForwardRegistered(String forwardName,
                                               List<ForwardReference> forwards) {
        assertThat(forwards)
            .withFailMessage("Expected forward '%s' to be registered but it was not found",
                forwardName)
            .extracting(ForwardReference::getName)
            .contains(forwardName);
    }

    public static void assertForwardEquals(ForwardReference expected, ForwardReference actual) {
        assertThat(actual).isNotNull();
        assertThat(actual.getName()).isEqualTo(expected.getName());
        assertThat(actual.getAddress()).isEqualTo(expected.getAddress());
    }

    // ========== Container Assertions ==========

    public static void assertContainerRunning(GenericContainer<?> container) {
        assertThat(container.isRunning())
            .withFailMessage("Container %s is not running", container.getDockerImageName())
            .isTrue();
    }

    public static void assertContainerHealthy(GenericContainer<?> container) {
        assertContainerRunning(container);
        // Additional health checks if needed
    }

    // ========== Capabilities Assertions ==========

    public static void assertCapabilitiesContainTool(Capabilities capabilities, String toolName) {
        assertThat(capabilities).isNotNull();
        assertThat(capabilities.getTools())
            .withFailMessage("Expected capabilities to contain tool '%s'", toolName)
            .extracting(ToolReference::getName)
            .contains(toolName);
    }

    public static void assertCapabilitiesContainResource(Capabilities capabilities,
                                                         String resourceName) {
        assertThat(capabilities).isNotNull();
        assertThat(capabilities.getResources())
            .withFailMessage("Expected capabilities to contain resource '%s'", resourceName)
            .extracting(ResourceReference::getName)
            .contains(resourceName);
    }

    // ========== Namespace Assertions ==========

    public static void assertNamespaceExists(String namespaceName, List<Namespace> namespaces) {
        assertThat(namespaces)
            .withFailMessage("Expected namespace '%s' to exist", namespaceName)
            .extracting(Namespace::getName)
            .contains(namespaceName);
    }

    // ========== Helper Methods ==========

    private static String getResponseBody(Response response) {
        try {
            return response.getBody().asString();
        } catch (Exception e) {
            return "<unable to read response body>";
        }
    }

    private static List<String> getToolNames(List<ToolReference> tools) {
        return tools.stream()
            .map(ToolReference::getName)
            .toList();
    }

    private static List<String> getResourceNames(List<ResourceReference> resources) {
        return resources.stream()
            .map(ResourceReference::getName)
            .toList();
    }
}
```

USAGE EXAMPLES
--------------

```java
// Instead of:
assertThat(response.isSuccess()).isTrue();
assertThat(response.getError()).isNull();

// Use:
WanakuAssertions.assertSuccessResponse(response);

// Instead of:
response.then().statusCode(200);

// Use:
WanakuAssertions.assertHttpSuccess(response);

// Instead of:
assertThat(tools).extracting(ToolReference::getName).contains("my-tool");

// Use:
WanakuAssertions.assertToolRegistered("my-tool", tools);
```

DELIVERABLES
------------
1. WanakuAssertions class with all custom assertions
2. Documentation on assertion usage
3. Example tests demonstrating assertions
4. Migration guide for existing tests

Git commit:
- "test(infra): Add custom assertions library"

VALIDATION
----------
- All assertions work correctly
- Clear failure messages displayed
- At least 10 existing tests migrated to use custom assertions
- Documentation is comprehensive

### PR DESCRIPTION
**Pull request by matheusandre1**
Closes: #561 

I made some adjustments to the test lessons, but we'll probably have to do this in several other classes as well.

## Summary by Sourcery

Introduce a shared Wanaku-specific test assertions library and apply it across HTTP, CLI, and namespace tests to standardize checks and improve failure messages.

Enhancements:
- Refactor REST-assured based router backend tests to use centralized HTTP status assertions while keeping response body validations intact.
- Replace scattered namespace name checks with custom namespace existence assertions to reduce duplication and clarify intent.
- Add Maven Surefire and Failsafe plugin configuration at the parent level to adjust JVM arguments for test execution.

Build:
- Expose AssertJ, RestAssured, and Testcontainers as provided/test-scoped dependencies in shared and CLI modules to support the new test assertion helpers.
- Adjust test wiring so backend tests no longer depend on the core-util test-jar while integration tests now consume the shared core-util assertions via a standard test dependency.

Documentation:
- Document the custom Wanaku assertions library and its usage patterns in the integration test documentation, including a migration guide for existing tests.

Tests:
- Adopt the new custom assertions in CLI tools label tests and router backend tests to assert HTTP and service responses more consistently.

## Summary by Sourcery

Introduce a shared Wanaku-specific test assertions library and adopt it across CLI and router backend tests to standardize HTTP, response, and namespace assertions.

Enhancements:
- Refactor HTTP-based router backend tests to use centralized HTTP status assertions while preserving existing response body checks.
- Replace direct namespace name checks in namespace tests with custom namespace existence assertions to reduce duplication and clarify intent.

Build:
- Expose core-util test-jar and common testing libraries (AssertJ, RestAssured, Testcontainers) as shared test dependencies in core-util, CLI, router-backend, and integration modules.

Documentation:
- Document the Wanaku custom assertions library, its usage patterns, and a migration guide in the integration test documentation.

Tests:
- Adopt the new custom assertions in CLI tools label tests and router backend HTTP/resource/tools tests to assert service and HTTP responses more consistently.

### CODE REVIEW

File: core/core-util/src/main/java/ai/wanaku/core/util/support/PromptsHelper.java
Comment (orpiske) [inline core/core-util/src/main/java/ai/wanaku/core/util/support/PromptsHelper.java:1]: This file should not have been moved.

File: core/core-util/src/main/java/ai/wanaku/core/util/support/ResourcesHelper.java
Comment (orpiske) [inline core/core-util/src/main/java/ai/wanaku/core/util/support/ResourcesHelper.java:1]: This file should not have been moved.

File: core/core-util/src/main/java/ai/wanaku/core/util/support/ToolsHelper.java
Comment (orpiske) [inline core/core-util/src/main/java/ai/wanaku/core/util/support/ToolsHelper.java:1]: This file should not have been moved.

File: core/core-util/src/test/java/ai/wanaku/test/assertions/WanakuAssertions.java [hunk 1]
```diff
@@ -0,0 +1,184 @@
+package ai.wanaku.test.assertions;
```
Comment (orpiske) [inline core/core-util/src/test/java/ai/wanaku/test/assertions/WanakuAssertions.java:1]: This should be in `src/test/` not `src/main` and part of a test-specific jar file.

File: tests/integration/ASSERTIONS.md [hunk 2]
```diff
@@ -0,0 +1,59 @@
+# Wanaku Assertions Library
+
+This module provides a domain-specific assertions helper designed to keep tests concise and to surface clear,
+actionable failure messages.
+
+**Location**
+`core/core-util/src/main/java/ai/wanaku/test/assertions/WanakuAssertions.java`
```
Comment (orpiske) [inline tests/integration/ASSERTIONS.md]: Same note as above (should be in `src/test` )

**Review by orpiske — CHANGES_REQUESTED** [review]
There are some issues to solve, but this is looking very promising!

File: core/core-util/src/main/java/ai/wanaku/core/util/support/ToolsHelper.java
Comment (matheusandre1) [reply core/core-util/src/main/java/ai/wanaku/core/util/support/ToolsHelper.java:1]: I put it in the wrong place.

File: core/core-util/pom.xml [hunk 3]
```diff
@@ -41,6 +41,22 @@
...
+        </dependency>
+        <dependency>
+            <groupId>io.rest-assured</groupId>
+            <artifactId>rest-assured</artifactId>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>org.testcontainers</groupId>
+            <artifactId>testcontainers</artifactId>
+            <scope>test</scope>
```
Comment (orpiske) [inline core/core-util/pom.xml]: Do we need testcontainers in the core tests? It does not look like we need it ...

File: parent/pom.xml [hunk 4]
```diff
@@ -207,6 +207,20 @@
...
+                    <version>${maven-surefire-plugin.version}</version>
+                    <configuration>
+                        <argLine>-Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
+                    </configuration>
+                </plugin>
+                <plugin>
+                    <artifactId>maven-failsafe-plugin</artifactId>
+                    <version>${maven-failsafe-plugin.version}</version>
+                    <configuration>
+                        <argLine>-Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
```
Comment (orpiske) [inline parent/pom.xml]: Please, why do we need this one?

**Review by orpiske — CHANGES_REQUESTED** [review]
This is looking really nice ... a few minor things to adjust, but you are on the right track. Thanks!

File: parent/pom.xml (hunk 4 above)
Comment (matheusandre1) [reply parent/pom.xml]: I will make the adjustments on my machine; without this, it will give an error.

File: core/core-util/pom.xml [hunk 5]
```diff
@@ -50,6 +60,18 @@
...
+            <groupId>org.assertj</groupId>
+            <artifactId>assertj-core</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>io.rest-assured</groupId>
+            <artifactId>rest-assured</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>org.testcontainers</groupId>
+            <artifactId>testcontainers</artifactId>
```
Comment (orpiske) [inline core/core-util/pom.xml:75]: This needs to have test scope only

File: core/core-util/pom.xml [hunk 6]
```diff
@@ -50,6 +60,18 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-qute</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.assertj</groupId>
+            <artifactId>assertj-core</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>io.rest-assured</groupId>
+            <artifactId>rest-assured</artifactId>
```
Comment (orpiske) [inline core/core-util/pom.xml:70]: This needs to have test scope only

File: core/core-util/pom.xml [hunk 7]
```diff
@@ -50,6 +60,18 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-qute</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.assertj</groupId>
+            <artifactId>assertj-core</artifactId>
```
Comment (orpiske) [inline core/core-util/pom.xml:65]: This needs to have test scope only

File: parent/pom.xml [hunk 8]
```diff
@@ -206,7 +206,7 @@
                             <arg>-parameters</arg>
                         </compilerArgs>
                     </configuration>
-                </plugin>
+                </plugin>
```
Comment (orpiske) [inline parent/pom.xml]: Unnecessary extra space here

**Review by orpiske — CHANGES_REQUESTED** [review]
Thanks ... This is moving on the right direction and the test code looks nice with it. The only remaining problem is that there are test dependendencies in runtime scope. We should not have those in runtime scope.

**Review by orpiske — APPROVED** [review]
Thanks, LGTM!
