### PR TITLE
Fix #917: use per-namespace OIDC tenants for correct resource metadata URLs

### LINKED ISSUE #917: OIDC authorization flow does not work for namespaces mcp resources /ns-*/mcp
The authorization flow fails for all namespaces mcp endpoints, take for instance mcp resource ns-1/mcp

**Request url**:  https://wanaku-backend.poc/ns-1/mcp
**Response code**: 401
**Response header www-authenticate**: 
Bearer resource_metadata="https://wanaku-backend.poc/.well-known/oauth-protected-resource/mcp"

the mcp resource metadata url returned in the www-authenticate response header is incorrect

There are 2 issues in my view

_Issue 1_: resource metadata url for resource ns-1/mcp endpoint should be 

https://wanaku-backend.poc/.well-known/oauth-protected-resource/ns-1/mcp rather than https://wanaku-backend.poc/.well-known/oauth-protected-resource/mcp

_issue 2_: calling the resource metadata url (https://wanaku-backend.poc/.well-known/oauth-protected-resource/ns-1/mcp) for resource ns-1/mcp  returns 404 Not Found. it should return this instead

`{"resource":"https://wanaku-backend.poc/ns-1/mcp","authorization_servers":["https://wanaku-backend.poc/q/oidc"]}`

### PR DESCRIPTION
**Pull request by orpiske**
## Summary

- Split the single `mcp` OIDC tenant into per-namespace tenants (ns-1 through ns-10) so each namespace advertises the correct `resource-metadata.resource` value (e.g., `ns-1/mcp` instead of just `mcp`)
- Added a custom `OAuthProtectedResourceWellKnownResource` endpoint to serve `/.well-known/oauth-protected-resource/{namespace}/mcp` with correct resource metadata JSON
- This fixes the incorrect `WWW-Authenticate` header in 401 responses and the 404 for namespace resource metadata endpoints

## Test plan

- [x] New integration tests for `/.well-known/oauth-protected-resource/{ns}/mcp` endpoint
- [x] Existing OIDC integration tests still pass
- [ ] Manual verification with Keycloak: access `/ns-1/mcp` unauthenticated and verify the `WWW-Authenticate` header points to `/.well-known/oauth-protected-resource/ns-1/mcp`
- [ ] Manual verification: `GET /.well-known/oauth-protected-resource/ns-1/mcp` returns correct resource metadata JSON

## Summary by Sourcery

Introduce per-namespace OIDC tenants and a well-known resource metadata endpoint to advertise correct MCP resource URLs per namespace.

New Features:
- Expose a /.well-known/oauth-protected-resource/{namespace}/mcp endpoint that returns resource metadata JSON for each namespace-specific MCP resource.

Bug Fixes:
- Ensure WWW-Authenticate and resource metadata URLs reference the correct namespace-specific MCP resource instead of the shared mcp resource.

Enhancements:
- Configure separate OIDC tenants for namespaces ns-1 through ns-10 so each namespace has its own resource metadata and tenant path configuration.
- Add integration tests verifying the namespace-specific oauth-protected-resource discovery endpoint returns correct resource and authorization server data.

### CODE REVIEW

**Comment by mescaja** [comment]
Thanks a lot for fixing, will test it tomorrow

**Comment by mescaja** [comment]
@orpiske, i think there's is a slight issue with the scheme http vs https

this is what i observed

**Test 1: expected outcome**

https://wanaku-backend.dev/mcp
www-authenticate Bearer resource_metadata="https://wanaku-backend.dev/.well-known/oauth-protected-resource/mcp"

https://wanaku-backend.dev/.well-known/oauth-protected-resource/mcp
{"resource":"https://wanaku-backend.dev/mcp","authorization_servers":["https://wanaku-backend.dev/q/oidc"]}

**Test 2: resource url scheme is http rather than https**

https://wanaku-backend.dev/ns-1/mcp
www-authenticate Bearer resource_metadata="http://wanaku-backend.dev/.well-known/oauth-protected-resource/ns-1/mcp"

https://wanaku-backend.dev/.well-known/oauth-protected-resource/ns-1/mcp
{"resource":"http://wanaku-backend.dev/ns-1/mcp","authorization_servers":["https://wanaku-backend.dev/q/oidc"]}

that's making testing of /ns-1/mcp MCP endpoint fail in MCP Inspector

File: apps/wanaku-router-backend/src/main/java/ai/wanaku/backend/api/v1/oidc/OAuthProtectedResourceWellKnownResource.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+    @ConfigProperty(name = "quarkus.oidc-proxy.root-path", defaultValue = "/q/oidc")
+    String oidcProxyRootPath;
+
+    @Context
+    UriInfo uriInfo;
+
+    @GET
+    @Path("/{namespace}/mcp")
+    public Response getProtectedResourceMetadata(@PathParam("namespace") String namespace) {
+        URI baseUri = uriInfo.getBaseUri();
```
Comment (orpiske) [inline apps/wanaku-router-backend/src/main/java/ai/wanaku/backend/api/v1/oidc/OAuthProtectedResourceWellKnownResource.java:30]: I think this is the culprit, @mescaja. Let me take a look ...
