### PR TITLE
fix: Command injection vulnerability in ExecClient

### LINKED ISSUE #953: Security: Command injection vulnerability in ExecClient
## Description

The ExecClient component contains a command injection vulnerability that allows arbitrary system command execution through tool configuration.

## Vulnerability Details

**File:** `capabilities/tools/wanaku-tool-service-exec/src/main/java/ai/wanaku/tool/exec/ExecClient.java:24-27`

**Issue:** The URI from tool invocation requests is treated as a file path, split by spaces, and executed directly via `ProcessRunner`. There is no input validation, command allowlisting, or sandboxing.

**Current Code:**
```java
public Object exchange(ToolInvokeRequest request, ConfigResource configResource) {
    ParsedToolInvokeRequest parsedRequest = ParsedToolInvokeRequest.parseRequest(request, configResource);
    LOG.infof("Invoking tool at URI: %s", parsedRequest.uri());
    File fullCommand = new File(parsedRequest.uri());
    String[] arguments = fullCommand.getAbsolutePath().split(" ");
    return ProcessRunner.runWithOutput(arguments);
}
```

## Steps to Reproduce

1. Register a tool with a URI containing shell metacharacters or space-separated arguments
2. Invoke the tool through the MCP router
3. The URI is split by spaces and executed as a system command without validation

## Expected Behavior

- Tool URIs should be validated against an allowlist of permitted executables
- Input should be sanitized and validated before execution
- Shell metacharacters should be rejected or properly escaped
- Execution should be sandboxed with appropriate permissions

## Actual Behavior

Any URI provided through tool configuration is executed as a system command without validation, allowing arbitrary command execution.

## Impact

An attacker who can register or modify tool configurations could execute arbitrary system commands with the privileges of the running process.

## Recommended Fix

1. Implement strict input validation for URIs
2. Add command allowlisting to restrict which executables can be run
3. Sanitize or reject shell metacharacters
4. Consider using a sandboxed execution environment
5. Log execution attempts for audit purposes

## Additional Context

This is part of a broader security audit of the Wanaku project. This vulnerability is rated CRITICAL and should be prioritized for immediate remediation.

### PR DESCRIPTION
**Pull request by matheusandre1**
Fixes: #953 

My question is regarding the CDI.

## Summary by Sourcery

Introduce an allowlisted, policy-driven execution model for the Exec tool to prevent command injection and unsafe process invocation.

New Features:
- Add an Exec command policy that tokenizes URIs, enforces an explicit executable allowlist, and validates commands before execution.

Bug Fixes:
- Prevent command injection in ExecClient by disallowing shell metacharacters, enforcing balanced quotes, and only running configured executables.

Enhancements:
- Refactor ExecClient to depend on injectable command policy and executor abstractions for safer, testable process execution.

Documentation:
- Document the new Exec tool executable allowlist configuration and update tool descriptions to reflect the stricter execution model.

Tests:
- Add unit and integration tests for ExecCommandPolicy, ExecClient security behavior, and the new command executor wiring.

## Summary by Sourcery

Introduce a policy-driven, allowlisted execution model for the Exec tool and route all process invocations through injectable command and executor abstractions.

New Features:
- Add an Exec command policy that tokenizes URIs into commands, validates them, and enforces an explicit executable allowlist before execution.
- Introduce a command executor abstraction for running validated commands, with a ProcessRunner-backed implementation.

Bug Fixes:
- Prevent command injection in ExecClient by rejecting unsafe characters, unbalanced quotes, blank commands, and non-allowlisted executables before running any process.

Enhancements:
- Refactor ExecClient to depend on injectable ExecCommandPolicy and CommandExecutor components instead of constructing and running raw file commands.
- Improve OS handling and script creation in tests by using RuntimeInfo helpers and UTF-8 encoding.

Documentation:
- Document the Exec tool's executable allowlist configuration and update tool descriptions to reflect the stricter, allowlist-based execution model.
- Add configuration reference for the new wanaku.service.exec.allowed-executables property.

Tests:
- Add unit tests for ExecCommandPolicy covering allowlist handling, tokenization, quoting, and rejection of unsafe commands.
- Add tests for ExecClient security behavior to verify that only allowlisted commands are passed to the executor and denied commands are never executed.
- Update integration tests for ExecClient to construct clients with the new policy and executor wiring.

### CODE REVIEW

File: capabilities/tools/wanaku-tool-service-exec/src/test/java/ai/wanaku/tool/exec/ExecCommandPolicyTest.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    @Test
+    void rejectsShellMetacharacters() throws Exception {
+        Path scriptPath = createScript(tempDir, "policy-meta");
+
+        ExecCommandPolicy policy = new ExecCommandPolicy(List.of(scriptPath.toString()));
+
+        assertThrows(SecurityException.class, () -> policy.buildCommand(scriptPath + " ; whoami"));
+    }
+
+    private static Path createScript(Path dir, String marker) throws IOException {
```
Comment (orpiske) [inline capabilities/tools/wanaku-tool-service-exec/src/test/java/ai/wanaku/tool/exec/ExecCommandPolicyTest.java:89]: This is duplicated code, I think ... so I'd rework the code to make it reusable

File: capabilities/tools/wanaku-tool-service-exec/src/test/java/ai/wanaku/tool/exec/ExecCommandPolicyTest.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        Files.createDirectories(dir);
+
+        boolean isWindows =
```
Comment (orpiske) [inline capabilities/tools/wanaku-tool-service-exec/src/test/java/ai/wanaku/tool/exec/ExecCommandPolicyTest.java]: I'd use the method from the RuntimeInfo class instead

File: capabilities/tools/wanaku-tool-service-exec/src/test/java/ai/wanaku/tool/exec/ExecCommandPolicyTest.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+                System.getProperty("os.name").toLowerCase(Locale.ROOT).contains("win");
+
+        String extension = isWindows ? ".cmd" : ".sh";
+        Path scriptPath = dir.resolve("exec-it-" + marker + extension).toAbsolutePath();
+
+        String content =
+                isWindows ? "@echo off\r\necho " + marker + "\r\n" : "#!/usr/bin/env sh\n" + "echo " + marker + "\n";
+
+        Files.writeString(scriptPath, content, StandardCharsets.US_ASCII);
```
Comment (orpiske) [inline capabilities/tools/wanaku-tool-service-exec/src/test/java/ai/wanaku/tool/exec/ExecCommandPolicyTest.java]: Why not UTF-8 here?

**Review by orpiske — CHANGES_REQUESTED** [review]
I think you are on the right track on this. I'm pointing out a few specific observations on the code.

File: capabilities/tools/wanaku-tool-service-exec/src/main/java/ai/wanaku/tool/exec/ExecCommandPolicy.java [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.List;
+import java.util.Set;
+
+@Singleton
+final class ExecCommandPolicy {
+    private static final Logger LOG = Logger.getLogger(ExecCommandPolicy.class);
```
Comment (orpiske) [inline capabilities/tools/wanaku-tool-service-exec/src/main/java/ai/wanaku/tool/exec/ExecCommandPolicy.java:17]: Minor: consider adding `\` (backslash) to `DISALLOWED_CHARACTERS` for defense in depth. While `ProcessBuilder` doesn't interpret shell escapes, rejecting backslashes strengthens the input validation layer.

File: capabilities/tools/wanaku-tool-service-exec/src/main/java/ai/wanaku/tool/exec/ExecCommandPolicy.java [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+        return Arrays.stream(allowedExecutables.split(","))
+                .map(String::trim)
+                .filter(entry -> !entry.isEmpty())
+                .toList();
+    }
+
+    private static String normalizeRequestedExecutable(String executable) {
+        if (executable == null || executable.isBlank()) {
+            throw new SecurityException("Command execution is denied because the executable path is blank");
+        }
```
Comment (orpiske) [inline capabilities/tools/wanaku-tool-service-exec/src/main/java/ai/wanaku/tool/exec/ExecCommandPolicy.java:73]: Nit: `Path.of(executable).toAbsolutePath()` silently resolves relative executables against CWD. This will almost certainly fail the allowlist check (which requires absolute paths), but the behavior is implicit. Consider explicitly rejecting non-absolute requested executables here, mirroring what `normalizeAllowlistedExecutable` does:

```suggestion
        Path path = Path.of(executable.trim());
        if (!path.isAbsolute()) {
            throw new SecurityException(
                    "Command execution is denied because the executable path must be absolute: " + executable.trim());
        }
        return path.toAbsolutePath().normalize().toString();
```

**Review by orpiske — APPROVED** [review]
## Review Summary

This PR addresses a critical command injection vulnerability (issue #953) with a well-structured allowlist-based approach. The implementation is solid — good separation of concerns, strong default-deny posture, and thorough test coverage.

### Minor suggestions (non-blocking)

- Consider adding `\` (backslash) to the `DISALLOWED_CHARACTERS` set for defense in depth.
- The `createScript` test helper is duplicated across three test files — a shared utility could reduce maintenance.
- `normalizeRequestedExecutable` resolves relative paths against CWD implicitly; consider explicitly rejecting non-absolute requested executables for clarity.
- Branch naming: `fix-953` vs convention `ci-issue-953` — minor mismatch.

Overall, well done — clean design and good coverage. 👍

This review does not replace specialized tools such as CodeRabbit, Sourcery, or SonarCloud.

_This review was generated by an AI agent and may contain inaccuracies. Please verify all suggestions before applying._
